package Paneles;

import Clases.CambiaPanel;
import static control_escolar_form.Prncipal.panelCentralx;
import Clases.Consultas;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.JTextField;

public class pnlAddAlum extends javax.swing.JPanel {
    pnlGrup grupos = new pnlGrup();
    Consultas consulta = new Consultas();
    static int eda;
    
    public pnlAddAlum() {
        initComponents();
        grado.setEditable(false);
        grupo.setEditable(false);
        grado.setText(grupos.todo[0]);
        grupo.setText(grupos.todo[1]);
        edades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nom_alumno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        appat_alumno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        apmat_alumno = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        curp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nom_tutor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        appat_tutor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        apmat_tutor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        limpiar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        grado = new javax.swing.JTextField();
        grupo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edad = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        ayuda = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 248, 253));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Alumnos");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gill Sans MT", 0, 24), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setName("asda"); // NOI18N
        jPanel1.setOpaque(false);

        nom_alumno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nom_alumno.setToolTipText("");
        nom_alumno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        nom_alumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nom_alumnoKeyTyped(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre(s)");

        appat_alumno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        appat_alumno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        appat_alumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                appat_alumnoKeyTyped(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Apellido Paterno");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Apellido Materno");

        apmat_alumno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        apmat_alumno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        apmat_alumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apmat_alumnoKeyTyped(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(130, 206, 130));
        guardar.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grupo/icons8_save_40px.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Grupo:");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("CURP");

        curp.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        curp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        curp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                curpKeyTyped(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Datos del tutor");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Nombre(s)");

        nom_tutor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nom_tutor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        nom_tutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nom_tutorKeyTyped(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Apellido Paterno");

        appat_tutor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        appat_tutor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        appat_tutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                appat_tutorKeyTyped(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Apellido Materno");

        apmat_tutor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        apmat_tutor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        apmat_tutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apmat_tutorKeyTyped(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Teléfeno");

        tel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        tel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Sexo");

        buttonGroup1.add(masculino);
        masculino.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        masculino.setForeground(new java.awt.Color(51, 51, 51));
        masculino.setText("Masculino");
        masculino.setToolTipText("H");
        masculino.setOpaque(false);

        buttonGroup1.add(femenino);
        femenino.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        femenino.setForeground(new java.awt.Color(51, 51, 51));
        femenino.setText("Femenino");
        femenino.setOpaque(false);

        limpiar.setBackground(new java.awt.Color(130, 206, 130));
        limpiar.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grupo/icons8_erase_40px.png"))); // NOI18N
        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Correo Electrónico");

        email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Grado:");

        grado.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        grado.setText("--");

        grupo.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        grupo.setText("--");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Edad: ");

        edad.setBackground(new java.awt.Color(204, 204, 255));
        edad.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        edad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                edadItemStateChanged(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(130, 206, 130));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grupo/icons8_undo_40px.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(27, 27, 27)
                                .addComponent(curp, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(masculino)
                                .addGap(18, 18, 18)
                                .addComponent(femenino)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(10, 10, 10)
                                        .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(grado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(11, 11, 11)
                                .addComponent(nom_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(11, 11, 11)
                                .addComponent(appat_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(apmat_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nom_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(appat_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apmat_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nom_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(appat_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(apmat_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masculino)
                            .addComponent(femenino)
                            .addComponent(jLabel5)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel13)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(nom_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(appat_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(apmat_tutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(limpiar)
                        .addGap(29, 29, 29)
                        .addComponent(guardar)))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu/icons8_children_64px_1.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ayuda.setBackground(new java.awt.Color(255, 255, 255));
        ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/help.png"))); // NOI18N
        ayuda.setToolTipText("Ayuda");
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /* Convierte el resultado de grado o telefono de String a Int */
    public long numero(JTextField campo){
       return Long.parseLong(campo.getText());       
    }
    
    /* Selecciona M o F dependiendo de la opcion elegida en el radio botton */
    public String genero(){
        String x = "";
        if (masculino.isSelected() == true && femenino.isSelected() == false) {
            x = "M";
        }else if (masculino.isSelected() == false && femenino.isSelected() == true){
            x = "F";
        }else{
            x = null;
        }    
        return x;
    }
    
    /* Campos que lleven String */
    public String campos(JTextField c){
        String x = "";
        if (c.getText().equalsIgnoreCase("")) {
            x = null;
            return x;
        }else {
            return c.getText(); 
        }    
        
    }
    
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        long p = numero(grado);
        long s = numero(tel);
        
        //SE VERIFICA SI HAY UN ALUMNO REGISTRADO CON EL MISMO NOMBRE 
        consulta.nombre(nom_alumno.getText(), appat_alumno.getText(), apmat_alumno.getText()); 
       
        if (Consultas.bandera) {
            consulta.altas(campos(nom_alumno), campos(appat_alumno), campos(apmat_alumno), campos(curp), p, grupo.getText(), genero(), eda, campos(nom_tutor), campos(appat_tutor), campos(apmat_tutor), s, campos(email));                                   
        
        }
    }//GEN-LAST:event_guardarActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new CambiaPanel(panelCentralx, new Paneles.pnlGrup());
    }//GEN-LAST:event_jButton2ActionPerformed

    /* Validaciones y Tamaño de campos*/   
    private void nom_alumnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_alumnoKeyTyped
        char x = evt.getKeyChar();
        if (nom_alumno.getText().length() <= 19) {
          if (((x < 'A' || x > 'Z') && x != ' ') && ((x < 'a' || x > 'z'))) {
            evt.consume();
          }  
        }else{
            evt.consume();
        }
        
    }//GEN-LAST:event_nom_alumnoKeyTyped

    private void appat_alumnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appat_alumnoKeyTyped
        char x = evt.getKeyChar();
        if (appat_alumno.getText().length() <= 19) {
            if (((x < 'A' || x > 'Z') && x != ' ') && ((x < 'a' || x > 'z'))) {
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_appat_alumnoKeyTyped

    private void apmat_alumnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apmat_alumnoKeyTyped
        char x = evt.getKeyChar();
        if (apmat_alumno.getText().length() <= 19) {
            if (((x < 'A' || x > 'Z') && x != ' ') && ((x < 'a' || x > 'z'))) {
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_apmat_alumnoKeyTyped

    private void curpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_curpKeyTyped
        char x = evt.getKeyChar();
        if (curp.getText().length() <= 17) {
            if (((x < 'A' || x > 'Z')) && ((x < '0' || x > '9'))) {
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_curpKeyTyped

    private void nom_tutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_tutorKeyTyped
        char x = evt.getKeyChar();
        if (nom_tutor.getText().length() <= 19) {
            if (((x < 'A' || x > 'Z') && x != ' ') && ((x < 'a' || x > 'z'))) {
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_nom_tutorKeyTyped

    private void appat_tutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appat_tutorKeyTyped
        char x = evt.getKeyChar();
        if (appat_tutor.getText().length() <= 19) {
            if (((x < 'A' || x > 'Z') && x != ' ') && ((x < 'a' || x > 'z')) && ((x != 'ñ' || x != 'Ñ'))) {
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_appat_tutorKeyTyped

    private void apmat_tutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apmat_tutorKeyTyped
        char x = evt.getKeyChar();
        if (apmat_tutor.getText().length() <= 19) {
            if (((x < 'A' || x > 'Z') && x != ' ') && ((x < 'a' || x > 'z')) && ((x != 'ñ' || x != 'Ñ'))) {
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_apmat_tutorKeyTyped

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped
        char x = evt.getKeyChar();
        if (tel.getText().length() < 10) {
            if (((x < '0' || x > '9'))) {
                evt.consume();
            }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_telKeyTyped

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        char x = evt.getKeyChar();
        if (email.getText().length() <= 50) {
        if (((x < 'A' || x > 'Z')) && ((x < 'a' || x > 'z')) && ((x < '0' || x > '9')) && ((x != '@')) && ((x != '.')) && ((x != 'ñ' || x != 'Ñ'))) {
            evt.consume();
        }
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_emailKeyTyped

    private void edadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_edadItemStateChanged
        System.out.println(edad.getSelectedItem());
        eda = Integer.parseInt(evt.getItem().toString());
    }//GEN-LAST:event_edadItemStateChanged

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
    
        JTextField[] txt = {curp, nom_alumno, appat_alumno, apmat_alumno, 
             nom_tutor, appat_tutor, apmat_tutor, tel, email};
        for (JTextField txt1 : txt) {
            txt1.setText("");
        }
        
    }//GEN-LAST:event_limpiarActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        if (Desktop.isDesktopSupported()) {
             try {                   
                    File manual = new File("C:\\Manual Tecnico.pdf#page=50");
                     
                    Runtime.getRuntime().exec("C:\\Program Files (x86)\\Internet Explorer\\iexplore.exe " + manual);
                    //Desktop.getDesktop().open(manual);
            } catch (IOException e) {
                        System.out.println(e);
                }
            }
    }//GEN-LAST:event_ayudaActionPerformed

    
    
    public void edades (){
        switch(grado.getText()){
            case "1":   edad.addItem("6");
                        edad.addItem("7");
                        break;
            
            case "2":   edad.addItem("7");
                        edad.addItem("8");
                        break;
                        
            case "3":   edad.addItem("8");
                        edad.addItem("9");
                        break;
                        
            case "4":   edad.addItem("9");
                        edad.addItem("10");
                        break;
                        
            case "5":   edad.addItem("10");
                        edad.addItem("11");
                        break;
                        
            case "6":   edad.addItem("11");
                        edad.addItem("12");
                        break;
                        
             case "":   edad.addItem("");
                        break;           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apmat_alumno;
    private javax.swing.JTextField apmat_tutor;
    private javax.swing.JTextField appat_alumno;
    private javax.swing.JTextField appat_tutor;
    private javax.swing.JButton ayuda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField curp;
    private javax.swing.JComboBox<String> edad;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JTextField grado;
    private javax.swing.JTextField grupo;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiar;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nom_alumno;
    private javax.swing.JTextField nom_tutor;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
